# Generated by Django 5.1.7 on 2025-03-13 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('WEB_DEV', 'Web Development'), ('ICT_SUPPORT', 'ICT Support'), ('TECH_TIPS', 'Tech Tips'), ('MAINTENANCE', 'Maintenance')], default='WEB_DEV', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
